# Generated by Django 4.2.2 on 2023-06-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15)),
                ('status', models.BooleanField(default=False)),
                ('last_checked', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='IPAddress',
        ),
    ]
